package helloJavaPackage;
//Generated by MyEclipse



public interface IHelloWebService {
	
	public String example(String message);
	public String day_schedule(String agent_id,String date,String cookie);
	public String make_order(String scheduleNo,int ticket_num,int child_num,String agent_id,String cookie,String cust,String tele,String price1,String price2,String amount);
	public String login(String agent_id,String password);
	public String change_password(String agent_id,String old_password,String new_password);
	public String pay_result(String agent_id,String orderNo,String result,String cookie);
	public String my_orders(String agent_id,String cookie);
	public String qry_order(String agent_id,String orderNo);
	public String cancel_order(String agent_id,String orderNo,String cookie);
	public String get_schedulePrice(String scheduleNo,String status);
	public String get_message(String msg);
	public String get_credit(String agent_id);
	public String one_schedule(String sno);
	
	public String mobile_verify(String phoneNum,String verifyCode);  //手机验证码登录
	public String mobile_login(String phoneNum,String passwd);  //手机登录
	public String mobile_add_order(String sno,String uno,int m_all,int m_adult,int m_child,float mpricea,
			 float mpricec,float mamount,String cardid,String mname,String cookie,String tele2);  //意向订单
	public String mobile_pay_order(String tmp_ono,String actno,String actname,float act_amt,String uno,String cookie);  //付费后，正式申请订单
	public String mobile_formal_order(String sno,String uno,int m_all,int m_adult,int m_child,float mpricea,
			 float mpricec,float mamount,String cardid,String mname,String cookie,String tele2);  //直接生成正式订单
	public String my_mobile_orders(String userId,String cookie);
	public String mobile_change_password(String userId,String old_password,String new_password);
	public String mobile_get_credit(String userId);
	
	public String my_history_orders(String agent_id,String cookie,String date1,String date2);
	public String get_agent_water(String agent_id,String date1,String date2);   //查询,日期格式yyyy-MM-dd
	public String get_agent_recharge(String agent_id,String date1,String date2);   //查询,日期格式yyyy-MM-dd
	public String get_agent_balance(String agentId);  //账户余额
	public String get_agent_order_amount(String agentId); //订单金额
	
	public String b2c_pay(String orderNo,String agent_id ,String phoneNum,float amt ,
			String bankText ,String operTimeStr );
	
	public String b2c_list(String agent_id,String refundAgentId,String date1,String date2,String cookie);
	
	public String b2c_refund(String agent_id,String paytime,String order_no,float amt,String cookie);
	public String make_order_web(String scheduleNo,int ticket_num,int child_num,String agent_id,String cookie,String cust,String tele,String price1,String price2,String amount,String specText);

	
	   } 


	
